#ifndef __ESP32_IOT_AZURE_IOT_HUB_EXT_H__
#define __ESP32_IOT_AZURE_IOT_HUB_EXT_H__

#include "esp32_iot_azure/azure_iot_hub.h"

#ifdef __cplusplus
extern "C"
{
#endif

    /**
     * @brief Initialize the Azure IoT Hub Client with a given device id, on a default server.
     * @note The hostname MUST BE configured in @ref CONFIG_ESP32_IOT_AZURE_HUB_SERVER_HOSTNAME.
     * @param[in] context IoT context.
     * @param[in] device_id Device id.
     * @return @ref AzureIoTResult_t with the result of the operation.
     */
    AzureIoTResult_t azure_iot_hub_init_default(azure_iot_hub_context_t *context,
                                                const utf8_string_t *device_id);

    /**
     * @brief Send telemetry data to IoT Hub, from a specific device component.
     * @note Contract: https://learn.microsoft.com/en-us/azure/iot-central/core/concepts-telemetry-properties-commands#telemetry
     * @param[in] context IoT context.
     * @param[in] component_name Component name.
     * @param[in] payload User defined telemetry payload.
     * @param[in] qos The QOS to use for the telemetry.
     * @param[out] packet_id Packet id for the sent telemetry, generated by the IoT context.
     * Can be notified of PUBACK for QOS 1 using the @ref AzureIoTHubClientOptions_t `xTelemetryCallback` option.
     * If \p qos is @ref eAzureIoTHubMessageQoS0 this value will not be sent on return. Can be `NULL`.
     * @return @ref AzureIoTResult_t with the result of the operation.
     */
    AzureIoTResult_t azure_iot_hub_send_telemetry_from_component(azure_iot_hub_context_t *context,
                                                                 const utf8_string_t *component_name,
                                                                 const utf8_string_t *payload,
                                                                 AzureIoTHubMessageQoS_t qos,
                                                                 uint16_t *packet_id);

#ifdef __cplusplus
}
#endif
#endif