name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ESP_DOCKER_IMAGE: gfurtadoalmeida/esp32-docker-sonar:v5.4

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}

    - name: Pull ESP-IDF Image
      shell: pwsh
      run: docker pull ${{env.ESP_DOCKER_IMAGE}}

    - name: Build
      shell: pwsh
      run: docker run --rm --env LC_ALL='C.UTF-8' -v ${{github.workspace}}:/project -w /project ${{env.ESP_DOCKER_IMAGE}} idf.py build

    - name: Build Test
      shell: pwsh
      run: docker run --rm --env LC_ALL='C.UTF-8' -v ${{github.workspace}}:/project -w /project ${{env.ESP_DOCKER_IMAGE}} idf.py -C ./test build

  release:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write

    env:
      ZIP_NAME: esp32-iot-azure.${{github.ref_name}}.zip

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Create Zip
      shell: bash
      run: |
        cp LICENSE components/esp32_iot_azure
        cd components
        zip -r ../${{env.ZIP_NAME}} esp32_iot_azure

    - name: Publish
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "${{env.ZIP_NAME}}"
        generateReleaseNotes: true
        makeLatest: true
        name: ESP32 IoT Azure ${{github.ref_name}}
        removeArtifacts: false
        replacesArtifacts: true
